#!/bin/bash
ZHE_TMP=$(mktemp)
awk 'BEGIN{print "divert(-1)"} {print $0} END{print "divert(0)dnl"}' "$1" > $ZHE_TMP
awk '{print $0}' "$2" >> $ZHE_TMP
ZHE_SELF_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ $3 = "" ]]; then
    awk -f "$ZHE_SELF_PATH/helper/zhe.awk" $ZHE_TMP | m4
else
    awk -f "$ZHE_SELF_PATH/helper/zhe.awk" $ZHE_TMP | m4 > "$3"
fi
